sudo: false

language: node_js
node_js: node

cache:
  directories:
    - elm-stuff/build-artifacts
    - elm-stuff/packages
    - sysconfcpus
os:
  - linux

env: ELM_VERSION=0.19.0

install:
  - node --version
  - npm --version
  - npm install -g elm@$ELM_VERSION elm-test@elm$ELM_VERSION elm-format@elm$ELM_VERSION

script:
  - elm-format --validate src tests examples
  - elm-test
